# BMad Data Practitioner dbt Project Configuration
name: 'bmad_data_practitioner'
version: '1.0.0'
config-version: 2

# Directory configuration
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Global variables
vars:
  # Security configuration
  security:
    require_authentication: true
    feature_flag: 'dbt_transformations'
    log_security_events: true
  
  # Data quality thresholds
  data_quality:
    completeness_threshold: 0.95
    uniqueness_threshold: 1.0
    validity_threshold: 0.98

# Model configuration
models:
  bmad_data_practitioner:
    # Staging models - one-to-one with source tables
    staging:
      +materialized: view
      +schema: staging
      +docs:
        node_color: "#E8F4FD"
    
    # Intermediate models - business logic transformations
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        node_color: "#FFF2CC"
    
    # Marts models - final analytics-ready datasets
    marts:
      +materialized: table
      +schema: marts
      +docs:
        node_color: "#D5E8D4"

# Test configuration
tests:
  +store_failures: true
  +schema: test_failures

# Snapshot configuration
snapshots:
  bmad_data_practitioner:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Documentation configuration
docs:
  generate: true

# On-run hooks for logging and monitoring
on-run-start: "{{ log('Starting dbt run at ' ~ run_started_at, info=true) }}"
on-run-end: "{{ log('Completed dbt run at ' ~ run_started_at, info=true) }}"

# Dispatch configuration for custom macros
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['bmad_data_practitioner', 'dbt_utils']