# Evidence.dev Configuration
# Modern configuration format for Evidence.dev v25.0.0
# Replaces evidence.plugins.yaml

plugins:
  components:
    "@evidence-dev/core-components": {}
  datasources:
    "@evidence-dev/duckdb": {}

theme:
  colorPalettes:
    default:
      light:
        - "#2563eb"  # BMad primary blue
        - "#64748b"  # BMad secondary gray
        - "#0f766e"  # Success green
        - "#dc2626"  # Error red
        - "#ea580c"  # Warning orange
      dark:
        - "#93c5fd"  # Light blue for dark mode
        - "#94a3b8"  # Light gray for dark mode
        - "#5eead4"  # Light green for dark mode
        - "#fca5a5"  # Light red for dark mode
        - "#fed7aa"  # Light orange for dark mode

datasources:
  analytics:
    type: "duckdb"
    filename: ".duckdb/analytics.db"
    # WASM Configuration for client-side processing
    extensions:
      - httpfs     # HTTP file system for remote data access
      - parquet    # Parquet format support
      - json       # JSON data processing  
      - fts        # Full-text search
      - spatial    # Geospatial data support
    options:
      memory_limit: "2GB"
      threads: 4
      enable_external_access: true
      # Optimization settings for analytical workloads
      enable_progress_bar: false
      enable_print_progress: false  
      enable_profiling: false
      max_memory: "1.5GB"
      temp_directory: ".duckdb/temp"
      # Performance tuning
      worker_threads: 2
      preserve_insertion_order: false
      enable_optimizer: true
      # Client-side processing optimization
      streaming_buffer_size: "64MB"
      checkpoint_threshold: "1GB"