name: bmad-data-practitioner
version: 1.0.0
short-title: Data Practitioner Agent System
description: >-
  Data Practitioner expansion pack for BMad Method - comprehensive data analysis
  workflows with modern data stack integration
author: Data Practitioner Agent System
slashPrefix: bmadData