features:
  pyairbyte_integration:
    enabled: true
    description: Enable PyAirbyte connectors for data ingestion
    dependencies: []
  duckdb_analytics:
    enabled: true
    description: Enable DuckDB for local analytics and data exploration
    dependencies: []
  dbt_transformations:
    enabled: false
    description: Enable dbt Core for data transformation workflows
    dependencies:
      - duckdb_analytics
  dagster_orchestration:
    enabled: false
    description: Enable Dagster for workflow orchestration
    dependencies:
      - pyairbyte_integration
      - duckdb_analytics
  eda_automation:
    enabled: true
    description: Enable automated exploratory data analysis
    dependencies:
      - duckdb_analytics
  automated_eda:
    enabled: true
    description: Enable automated EDA using pandas-profiling, Sweetviz, and AutoViz
    dependencies: []
  agent_hypothesis_generation:
    enabled: true
    description: Enable agent-based hypothesis generation from EDA reports
    dependencies: []
  statistical_testing:
    enabled: true
    description: Enable automated statistical testing framework
    dependencies: []
  pattern_detection:
    enabled: true
    description: Enable pattern detection and anomaly identification
    dependencies: []
  evidence_publishing:
    enabled: false
    description: Enable Evidence.dev for data publication
    dependencies:
      - duckdb_analytics
      - dbt_transformations
  qa_framework:
    enabled: false
    description: Enable comprehensive QA and documentation framework
    dependencies: []
  sqlmesh_transformations:
    enabled: false
    description: Enable SQLmesh for data transformation workflows with cost optimization
    dependencies:
      - duckdb_analytics
metadata:
  version: 1.0.0
  last_modified: '2025-08-17T15:31:12.216Z'
  environment: development
safety:
  require_explicit_enable: true
  disable_on_error: true
  log_all_changes: true
rollback_triggers:
  - error_rate_threshold: 0.1
  - memory_usage_threshold: 0.9
  - response_time_threshold: 5000
